# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # frozen: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "6fd1ced85fc139abd7f5ab4f3d78dab37592cd5e" # frozen: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        types_or: [css, javascript, ts, tsx]
        args: [--write]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: ce0d77ac47dc921b62429804fe763d4d35f66a76  # frozen: v0.34.0
    hooks:
    - id: markdownlint
      args: [--config, .markdownlint.json]
